<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HyperQuestRunner</AssemblyName>
    <RootNamespace>HyperQuestRunner</RootNamespace>
    <Version>3.3.0</Version>
    <Description>Hyper AutoFarm Quest - High Performance C# .NET WinAPI Dummy Game Sleeper & Discord Named Pipe IPC</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipes" Version="4.3.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.3" />
    <PackageReference Include="Spectre.Console" Version="0.48.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

</Project>
